<?php


get_header("child");

/**
 * TODO: when display all USERS => change page title
 */

//> users mean in current context ==> taxonomy term(s) name(s)
const TAXONOMY = "users";
$users = explode(",", $wp->query_vars[TAXONOMY]);

//> get term(s) id(s) by term(s) name(s)
$term_query = new WP_Term_Query(
	array(
		"taxonomy"		=> TAXONOMY,
		"name"			=> $users,
		"fields"		=> "ids",
		"order"			=> "DESC",
		"hide_empty"	=> false,
	)
);

$terms_ids = $term_query->terms;

//> array_map using anonymous arrow lambda function
$gitlabs_ids = array_map(
	fn($term_id): string => get_term_meta($term_id, "gitlab_id", true),
	$terms_ids
);


foreach ($gitlabs_ids as $gitlab_id) {
	$user_projects = get_projects($gitlab_id);
	echo gl_projects_markup($user_projects, $gitlab_id);
}

echo "current gitlab_id: " . $gitlab_id . "<br>";

$cron_user = get_user_by("login", "cron");
$cron_id = $cron_user->ID;
$project_post_params = array(
	"post_author"	=> $cron_id,
	// "post_date"		=> "",
	// "post_content"	=> "",
	"post_title"	=> "CPT Generated by Cron",
	"post_status"	=> "publish",
	"post_type"		=> "gl_project",
	"post_category"	=> $terms_ids,
);

//$result = wp_insert_post($project_post_params);
//echo "wp_insert_post: " . $result;

//==============================================================================

// print "<br>";
get_footer();

//==============================================================================
// GitLab projects markup
function gl_projects_markup($projects, $user_id) {
	ob_start();
?>

	<div class="projects"><!-- START#div.projects-title -->
		<header class="projects-header">
			<h1 class="projects-title">
				GitLab projects for userID: <?php echo $user_id; ?>
			</h1>
		</header>
		<ul class="projects-list"><!-- START# ul.projects-title-list -->
		<?php foreach ($projects as $project): ?>
			<li>
				<a href="<?php echo $project->web_url; ?>">
				<?php echo $project->name; ?>
				</a>
			</li>
		<?php endforeach; ?>
		</ul><!-- END# ul.projects-title-list -->
	</div><!-- END#div.projects-title -->

<?php
	return ob_get_clean();
}

//==============================================================================
// get GitLab projects
function get_projects($user_id, $amount = 2) {
	$response = wp_remote_get(
		"https://gitlab.com/api/v4/users/${user_id}/projects?per_page=${amount}"
	);
	return json_decode($response["body"]);
}
